on:
  push:
    branches:
      - main
 
name: Deploy into Azure Container App
 
jobs:
  build-and-deploy:
    runs-on: self-hosted
    env:
      ACTIONS_RUNNER_DEBUG: true
 
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
 
      - name: Debug Log
        run: |
          echo "ACTIONS_RUNNER_DEBUG is: $ACTIONS_RUNNER_DEBUG"
          echo "GitHub SHA: ${{ github.sha }}"
          echo "Azure Credentials: ${{ secrets.AZURE_CREDENTIALS }}"
          echo "Registry Login Server: ${{ secrets.REGISTRY_LOGIN_SERVER }}"
          echo "Registry Username: ${{ secrets.REGISTRY_USERNAME }}"
          echo "Registry Password: ${{ secrets.REGISTRY_PASSWORD }}"
 
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
 
      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
 
      - run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.sha }}
 
      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          acrName: testacrcontainerapp
          containerAppName: testapp
          resourceGroup: test-rg
          imageToDeploy: ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.sha }}
